version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://server:8081
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "8081:8081"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/cart
      - NODE_ENV=production
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cart

volumes:
  mongo-data: